//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boodschapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paid
    {
        public int id { get; set; }
        public string user_id_sender { get; set; }
        public string user_id_receiver { get; set; }
        public string amount { get; set; }
        public string created_at { get; set; }
    }
}
